disable_all_formatting = true
max_width = 80
unstable_features = true
edition = "2015"
brace_style = "AlwaysNextLine"
mod_brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_brace_style = "AlwaysNextLine"
item_brace_style = "AlwaysNextLine"

tab_spaces = 3